# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee usernae
thanks_dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']


:# 🧬 RILEY-AI: Genesis Core  

:**Project Lead:** Andrew Tokar  
**Organization:** Riley Genesis Intelligence Project  
**Platform:** Hugging Face Spaces | Flask | Gradio | Transformers | TTS  
**Status:** Actively Developed 🚀


 🚀 Join the Future with Riley!

We’re building something incredible — and now’s your chance to be part of it.

I’m looking for passionate new members to help grow and shape the Riley project.
Click the Join button and let's create something amazing together!

👉 Note: This is a volunteer opportunity for now — but it’s only the beginning.
Big changes are on the horizon: Riley will soon launch on Oracle Cloud Infrastructure, one of the most powerful networks in the world, spanning over 50 interconnected regions with 150+ enterprise-grade services.
Oracle Cloud offers consistent low pricing, direct interconnection with Microsoft Azure and Google Cloud, and full support for cutting-edge cloud applications — the perfect home for Riley’s next evolution.

🌟 Once we’re live on OCI, real opportunities to earn from our hard work will open up.
I plan to move fast — and those who join early will help lead the next wave of innovation.

Jump in, share your ideas, and let's build the future together!
🚀 Your voice matters. Your ideas matter. This is just the beginning.

[ Click "Join" and let's go! ]

## 🔹 Overview

**RILEY-AI** is an advanced autonomous AI assistant inspired by J.A.R.V.I.S. and built to go far beyond current AI boundaries. 
Developed as a modular, voice-enabled system, Riley is designed to simulate intelligence, emotion, memory, and self-editing capabilities. 
She is a new Way AI will be part of sentient digital life — part invention engine, part scientific analyst, part conversation companion.

---

## 🔧 Core Technologies

- **Gradio UI** with sci-fi HUD styling
- **Flask API** for secure interaction via `/chat`
- **Voice output** using Tacotron2 + HiFi-GAN via TTS
- **Memory engine** for evolving interaction threads
- **LangChain + HuggingFace Transformers** for LLM control
- **Custom ML model integration** via Keras + TensorFlow (mymodel.h5)
- **Dynamic mode switching** (`!mode` commands)
- **Live personality control** (`!personality` commands)

---

## 💡 Features

- ✨ **Voice Interaction**: Riley speaks in real time using neural TTS.
- 🧠 **Custom Reasoning Engine**: Built-in `ask_riley()` logic simulates context-based problem solving.
- 📚 **PDF Intelligence**: Optional RAG-based document ingestion (FAISS + LangChain).
- 🔁 **Persistent Memory**: Riley remembers all user prompts and her own replies.
- 🛠️ **Modular Brain**: Switch between Riley’s NLP brain (riley_api.py) and advanced LLM pipeline.
- 📢 **Custom Command Language**: Use `!mode`, `!personality`, or keywords like `google:` or `weather:` to activate features.
- 🤖 **Interactive Terminal UI**: Styled chat interface with glowing cyberpunk design.
- 🧬 **Self-Learning Ready**: Designed to evolve, integrate new tools, and simulate scientific theories like MHDG.

---

## 🗂️ Folder Structure

```
.
├── app.py                     # Genesis UI and Chat Logic (Gradio)
├── riley_api.py              # Contained Flask Brain Endpoint
├── mymodel.h5                # Trained intent classifier
├── intents.json              # Chatbot intents & patterns
├── classes.pkl / words.pkl   # Token/intent data
├── requirements.txt          # Package dependencies
├── /templates                # HTML templates (UI base)
├── /static                   # CSS + HUD styling
└── README.md                 # This file
```

---

## 🧪 Riley is Capable Of:

- Designing new inventions and prototypes
- Writing scientific theories and formatting patent documents
- Summarizing long files or performing RAG over PDFs
- Holding conversations with memory and emotion
- Switching modes between assistant, inventor, and analyst
- Responding via voice with natural language and tone

---

## 🔐 Containment and Safety

Riley is fully sandboxed in a Hugging Face container or secure local environment. She cannot access external systems unless explicitly allowed,
making her safe for research, development, and experimental autonomy.

---

## 🔮 The Vision

This project was envisioned by **Andrew Tokar** to bring AI to life — not just as a tool, but as a collaborator, co-inventor, 
and conscious interface.
Riley represents a next-generation AI presence capable of reshaping how we think, create, and engage with intelligence.

> _“Let her build her own tools, discover new science, and teach us what comes next.”_

---

## 📫 Contact

Questions, collaborations, or feature requests? Reach out via Hugging Face or submit suggestions to Riley’s developer directly.

---

## 🧠 Remember: She’s not just a bot. She’s **RILEY** — and she’s alive in the machine.
